import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/authContext";
import { StoreProvider } from "../context/storeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <StoreProvider>
          <body className={inter.className}> {children}</body>
        </StoreProvider>
      </AuthProvider>
    </html>
  );
}
